language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_github avantcredit/aws-tools"
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r stringr"
- "./travis-tool.sh install_r testthat"
- "./travis-tool.sh install_github jimhester/covr"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
  - "Rscript -e 'library(covr);coveralls()'"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    rooms:
      secure: inqJiqV/C+/gOaxInYn9RmpG0zTSAXIUq17c+C1PLeSc+1ESeaHETdV5cI7r5WTr7AHLFPSAnZ5Q31RCMiryu7xpYgOQVVQeIUL7TQ/KfKIT0cjy6MhvKHNAlYfOAGtA1NqB+X63zj3DIAfSCz3G38HtK9NydXS9ZuCI1OVi1lc=
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
